SC-9192 Fix path mapping
hpi-schul-cloud/superhero-dashboard pull request #120
Opened 2021-07-23 11:42 UTC by uidp

# Description
access server api by dedicated version prefix. currently only `/v1` for the feathers api is used.

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-07-27 13:20 UTC, tofixx approved these changes

2021-08-10 14:53 UTC, tofixx submitted a review, later dismissed

2021-08-13 07:22 UTC, virgilchiriac submitted a review, later dismissed

2021-08-13 09:37 UTC, mamutmk5 requested changes

2021-08-13 09:45 UTC, mamutmk5 commented on api.js
> +const api = (req, { useCallback = false, json = true, version = 'v1' } = {}) => {
It is possible to solve the _v1_ part without a breaking change?

2021-08-16 07:24 UTC, mamutmk5 approved these changes

2021-08-16 07:53 UTC, merged