N21-341 switch hydra calls to api v3
hpi-schul-cloud/superhero-dashboard pull request #179
Opened 2022-09-30 08:09 UTC by MarvinOehlerkingCap

# Description
Switch the CRUD operations for Hydra oauth2 clients to the v3 nest api

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/N21-341

## Changes

## Datasecurity

## Deployment
Introduced environment variable: FEATURE_LEGACY_HYDRA_ENABLED. should be unset or false.

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-10-04 10:49 UTC, alweber-cap requested changes

2022-10-04 10:49 UTC, alweber-cap commented on controllers/tools.js
> +    return process.env.FEATURE_LEGACY_HYDRA_ENABLED ? 'v1' : 'v3';
add an additional case for when the variable is not available.

2022-10-04 13:10 UTC, alweber-cap submitted a review, later dismissed

2022-10-04 15:11 UTC, Metauriel submitted a review, later dismissed
this should be tested by QA before merging

2022-10-10 10:29 UTC, Loki-Afro approved these changes

2022-10-10 11:31 UTC, Metauriel approved these changes

2022-10-10 11:32 UTC, merged